services:
  - type: web
    name: my-fastapi-app-backend
    env: python
    pythonVersion: "3.9"
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mydatabase
          property: connectionString
      - key: TOGETHER_API_KEY
        sync: false

databases:
  - name: mydatabase
    plan: free